spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070

eurekaserver1:
  instance:
    hostname: eurekaserver1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - http://eurekaserver2:8073/eureka/
        - http://eurekaserver3:8074/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

eurekaserver2:
  instance:
    hostname: eurekaserver2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - http://eurekaserver1:8070/eureka/
        - http://eurekaserver3:8074/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

eurekaserver3:
  instance:
    hostname: eurekaserver3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - http://eurekaserver1:8070/eureka/
        - http://eurekaserver2:8073/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
